### ISSUE TITLE
Can we remove Express entirely?

### ISSUE THREAD

**Issue by nelspd915** [nelspd915/codenames#17]
If we are using socket.io for all interaction between the client and server, do we even need an Express server at all? If not, we can remove it from the backend code.

**Comment by Saguuu** [comment]
It does seem a little weird but from what I understand you need an http server running in order for socket.io to function correctly since it is not a direct web socket implementation. Don't necessarily need to use express, technically we could just use node's built in http which might suffice, but I think express would be more useful since it works well with mongoose / MongoDB. [This Stackoverflow thread explains it a bit](https://stackoverflow.com/questions/37836130/socket-io-why-does-it-need-an-http-server#:~:text=Websocket%20is%20created%20when%20you,kind%20of%20does%20need%20http.&text=socket.io%20isn't%20a,for%20its%20initial%20connection%20setup.), [as well as some documentation](https://socket.io/get-started/chat). I could look into it more.

**Comment by nelspd915** [comment]
Ok sounds good

**Comment by nelspd915** [comment]
Oh I think I get it, I'm guessing socket.io interacts with the http server running on port 8080 under the hood. Even if the socket connection from the client comes through a different port. So ya keeping Express makes sense
